version: '3'

networks:
    laravel:

services:
    # httpd:
    #     image: httpd:alpine
    #     container_name: apache
    #     ports:
    #         - 8088:80
    #     depends_on:
    #         - php
    #         - mysql
    #     volumes:
    #         - ./src:/var/www/html
    #         - ./httpd/laravel.conf:/etc/apache2/sites-available/laravel.conf
    #     networks:
    #         - laravel
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - 8080:80
        volumes:
            - ./src:/var/www/html:cached
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:5.7.22
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql:cached
        environment:
            MYSQL_DATABASE: docker
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - ./src:/var/www/html:cached
        ports:
            - 9000:9000
        networks:
            - laravel

    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - ./src:/var/www/html:cached
        working_dir: /var/www/html
        networks:
            - laravel

    npm:
        image: node:alpine
        container_name: npm
        volumes:
            - ./src:/var/www/html:cached
        working_dir: /var/www/html
        entrypoint: ['npm']
        networks:
            - laravel

    artisan:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: artisan
        volumes:
            - ./src:/var/www/html:cached
        depends_on:
            - mysql
        working_dir: /var/www/html
        entrypoint: ['/var/www/html/artisan']
        networks:
            - laravel
